#ifndef LEXER_H
#define LEXER_H

typedef enum{
    TOKEN_LET,
    TOKEN_ADD,
    TOKEN_MUL,
    TOKEN_SUB,
    TOKEN_DIV,
    TOKEn_PRINT,
    TOKEN_TOSTR,
    TOKEN_TOINT,
    TOKEN_IF,
    TOKEN_THEN,
    TOKEN_ELSEIF,
    TOKEN_ELSE,
    TOKEN_ENDIF,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_EXCLAMATION,
    TOKEN_QUESTION,
    TOKEN_IDENTIFIER
}